version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs",
    "meteor",
    "ember",
    "vue"
  ]
  environment = [
    "nodejs",
    "jquery",
    "mongo",
    "browser",
    "cypress",
    "jest",
    "mocha",
    "vitest",
    "jasmine"
  ]

[[analyzers]]
name = "php"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"